erlang-native: Add missing dependency
[Error #1]
configure: error: No curses library functions found

[Error #2]
crypto.c:37:33: fatal error: openssl/opensslconf.h: No such file or
directory

[GDP-681] Pyro: Fix build error in erlang-native
[GDP-605] Upgrade base system to Yocto 2.3 / Pyro branch

Signed-off-by: Changhyeok Bae <changhyeok.bae@gmail.com>